### PR TITLE
Building chromium for v3.0.*

### PR DESCRIPTION
**Pull request by fartbagxp**
- Adding new built binaries for [puppeteer 3.0.x releases](https://github.com/puppeteer/puppeteer/releases)

### CODE REVIEW

**Comment by bestplay9384** [comment]
@fartbagxp did you add `libgbm-dev` dependency while compiling as authors stated in puppeteer 3.0.1 release:

> The docs now include the libgbm-dev dependency that's needed for Linux builds (#5667, #5693)

Linked issues:
* https://github.com/puppeteer/puppeteer/pull/5667
* https://github.com/puppeteer/puppeteer/pull/5693

I'm asking because those issues are connected especially with lambda environment :)

**Comment by bestplay9384** [comment]
As far as i tested (via lambda layer) it works fine :)

**Comment by fartbagxp** [comment]
Hmm, @bestplay9384 - didn't notice that one.
I just ran https://github.com/alixaxel/chrome-aws-lambda/blob/master/_/ansible/plays/chromium.yml using ansible, should the `Install Packages` include libgbm-dev?

What else is missing - since chromium.yml hasn't been updated since Oct 2019?

I can try to rebuild it with everything else turned on.

**Comment by fartbagxp** [comment]
It doesn't seem like `libgbm1` is available, so I'll use `libgbm1-dev` and update the configurations before rebuilding. I noticed that the AMI in `inventory.ini` is running off of a 2019 version of Amazon Linux 2 but it's probably not an issue.

I'm adding the hashes of the new files, just in case anybody wanted to verify.

| File               | Type of Hash | Hash                                                             |
| ------------------ | ------------ | ---------------------------------------------------------------- |
| chromium.br        | md5          | 6e1eeb438f88880d41b70e8a33db29db                                 |
| chromium.br        | sha1         | 49c57d369423c27189aec03b4487fb5da75e198b                         |
| chromium.br        | sha256       | aaebb14231f2c80e5afd15586c1d94b6780f7ed1dcbe2b044c86592207e231d6 |
| swiftshader.tar.br | md5          | 5570df5549a9faaebb3b2a3d4cbd4e84                                 |
| swiftshader.tar.br | sha1         | e44214200c893af265c24a2dabc738981813bcbf                         |
| swiftshader.tar.br | sha256       | b42101c710e59a68d89e38b8006262f7ad0409793ae979214e5ea6ea35241d31 |

**Comment by alixaxel** [comment]
Thank you for this @fartbagxp! :bow:

**Pull request closed without merging**
