### PR TITLE
Fix return value in README

### PR DESCRIPTION
**Pull request by garrettseward**

### CODE REVIEW

**Comment by alixaxel** [comment]
@garrettseward The response payload that you provided:

```js
{
  body: result,
  headers: { 'Content-Type': 'text/plain' },
  statusCode: 200,
}
```

Is specific to API Gateway integrations. Since the scope of this project is broader than Lambda + API Gateway, I think it doesn't make much sense to show that payload in a getting started example.

Thank you for the PR though! :muscle:

**Comment by garrettseward** [comment]
The name of this project literally includes the words "aws-lambda".

**Comment by alixaxel** [comment]
@garrettseward AWS Lambda != AWS API Gateway. :wink:

**Comment by garrettseward** [comment]
Very true! Thanks for the work on this.

**Pull request closed without merging**
