### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by franz101**

### CODE REVIEW

**Comment by mg98** [comment]
Thanks for making these pull requests... but why did you split the changes into 4 separate PRs?

**Comment by franz101** [comment]
Sorry I was on my mobile phone

**Comment by heathera2016** [comment]
Thanks for your contribution. @franz101 It seems puppeteer 5.2.1 changed the path again over 5.1

**Comment by franz101** [comment]
let me see if I can clean it up and create a proper merge request.

**Pull request closed without merging**
