### PR TITLE
Move dependencies from dev to prod

### PR DESCRIPTION
**Pull request by buresmi7**
When include this project from another I need to add dependencies `@types/puppeteer` and `iltorb`. This MR solves it.

### CODE REVIEW

**Comment by alixaxel** [comment]
@buresmi7 I'm curious why you feel you need to do this.

The `iltorb` dependency are bundled with this package, so in theory you don't need to install it.
Unless you're not running on AWS Lambda, that is.

As for the `@types/puppeteer` it's only type definitions for Typescript projects, so I also don't see why you'd want to declare them as a production dependency.

**Comment by buresmi7** [comment]
@alixaxel my example package.json
```
"devDependencies": {
  "chrome-aws-lambda": "^1.18.0",
  "iltorb": "^2.4.3", // every project including chrome-aws-lambda needs this two next dependencies
  "@types/puppeteer-core": "^1.9.0",
}
```
I think that should be one dependency to write to package.json. But you are right, that `@types/puppeteer-core` is usable only for typescript project - I agree, that should not be in prod dependencies.

iltorb:
https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js#L200
It is needed for CI that do not run on cloud.

**Comment by alixaxel** [comment]
@buresmi7 You could try setting `AWS_EXECUTION_ENV=AWS_Lambda_nodejs8.10`.

Alternatively, you could also declare `iltorb` in `optionalDependencies`.

Regardless, this PR, under certain environments, will create problems in production, so I won't be merging it.

**Comment by buresmi7** [comment]
Thanks for reply.

**Pull request closed without merging**
