### PR TITLE
Fix require path for puppeteer-core 5.2.x

### LINKED ISSUE #154: [BUG] Cannot find module 'puppeteer-core/lib/Browser'
Trying to execute README example, the following error occurred. 

## Environment
* `chrome-aws-lambda` Version: 3.1.1
* `puppeteer` / `puppeteer-core` Version: 5.1.0
* OS: Linux 
* Node.js Version: 12.x 
* Lambda / GCF Runtime: nodejs12.x

## Expected Behavior
Should have returned example.com content.

## Current Behavior
Following error occurs:
```
Lambda execution failed with status 200 due to customer function error:  Cannot find module 'puppeteer-core/lib/Browser'
Require stack:
- /var/task/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js
- /var/task/node_modules/chrome-aws-lambda/source/index.js
- /var/task/app.js
```
No Browser module expored in the following path: 'puppeteer-core/lib/Browser'

## Steps to Reproduce
Lambda functions:  memory is 1024M, timeout is 3000ms.
```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    let page = await browser.newPage();

    await page.goto(event.url || 'https://example.com');

    result = await page.title();
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

### PR DESCRIPTION
**Pull request by ik1ne**
Fixes #154 .
It was already handled for puppeteer full version with commit f4d1fed53f0a20782900483b7c11539ba13faad9, but the path for puppeteer-core was not fixed.

### CODE REVIEW

**Comment by h1f1x** [comment]
closes: #158

**Comment by tomanagle** [comment]
Is this going to be merged soon?

**Comment by h1f1x** [comment]
Dear @alixaxel, if you are so kind and could merge this bugfix soon?
We would really appreciate it, as this is blocking a lot of people from using your nice project ;).

**Comment by jnd0** [comment]
Yes Please @alixaxel  

Also thanks @h1f1x @tomanagle @ik1ne for fixing and keeping track of this.

**Comment by alixaxel** [comment]
@h1f1x Apologies, work has been keeping me super busy lately - thanks for the heads up.

@ik1ne Thank you, I will be publishing a patch version with this shortly.

**Pull request merged**
